name: Scheduled OWASP ZAP baseline scan

on:
  schedule:
    # Runs every day at 01:00 Singapore Standard Time (SGT)
    - cron: '0 17 * * *'
  # workflow_run:
  #   workflows: [Deploy to AWS Lambda]
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    name: Scan the microservice application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan on EventSpark Microservice
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://bqqn2os7e1.execute-api.ap-southeast-1.amazonaws.com/stg'
          cmd_options: '-a'
